{
    'name': 'Hospital Management, by Nuhaadh',
    'version': '4.1',
    'category': 'Extra Tools',
    'summary': 'Module for managing the Hospitals',
    'sequence': 1,
    'author': 'Nuhaadh Hassan',
    'depends': ['mail', 'sale', 'crm', 'board', 'web_notify'],
    'demo': [],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/sequence.xml',
        'wizards/create_appointments.xml',
        'views/appointments.xml',
        'views/patients.xml',
        'views/lab.xml',
        'views/doctors.xml',
        'views/setting.xml',
        'views/sale_orders.xml',
        'views/dashboard.xml',
        'views/connect.xml',
        'views/template.xml',
        'views/website_form.xml',
        'reports/report.xml',
        'reports/sale_report_inherit.xml',
        'reports/patients_card.xml',
        'reports/appointments.xml',
        'data/data.xml',
        'data/cron.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False
}
